#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const { execSync } = require("child_process");

const LESSONS_DIR = "./lessons";

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function ask(question) {
    return new Promise(resolve => {
        rl.question(question, answer => {
            resolve(answer.trim());
        });
    });
}

function slugify(text) {
    return text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");
}

function titleCase(text) {
    return text
        .split("-")
        .map(word =>
            word.charAt(0).toUpperCase() +
            word.slice(1)
        )
        .join(" ");
}

function getFolders() {

    if (!fs.existsSync(LESSONS_DIR)) {
        fs.mkdirSync(LESSONS_DIR);
    }

    return fs.readdirSync(LESSONS_DIR)
        .filter(folder => {

            const full =
                path.join(LESSONS_DIR, folder);

            return fs.statSync(full).isDirectory();
        })
        .sort();
}

function getNextFolderNumber() {

    const folders = getFolders();

    if (!folders.length) {
        return "001";
    }

    const max = Math.max(
        ...folders.map(folder =>
            parseInt(folder.split("-")[0])
        )
    );

    return String(max + 1)
        .padStart(3, "0");
}

function getNextPageNumber(folderPath) {

    const files = fs.readdirSync(folderPath)
        .filter(file => file.endsWith(".html"));

    if (!files.length) {
        return "001";
    }

    const max = Math.max(
        ...files.map(file =>
            parseInt(file.split("-")[0])
        )
    );

    return String(max + 1)
        .padStart(3, "0");
}

async function createChapter() {

    console.log("\nExisting Chapters:\n");

    getFolders().forEach((folder, index) => {
        console.log(`${index + 1}. ${folder}`);
    });

    const name = await ask(
        "\nChapter Name: "
    );

    const slug = slugify(name);

    const duplicate =
        getFolders().find(folder =>
            folder.endsWith(slug)
        );

    if (duplicate) {
        console.log(
            "\nChapter already exists.\n"
        );
        return;
    }

    const order =
        getNextFolderNumber();

    const folderName =
        `${order}-${slug}`;

    const fullPath =
        path.join(
            LESSONS_DIR,
            folderName
        );

    fs.mkdirSync(fullPath);

    console.log(
        `\n✓ Created ${folderName}\n`
    );
}

async function createPage() {

    const folders = getFolders();

    if (!folders.length) {
        console.log(
            "\nNo chapters exist.\n"
        );
        return;
    }

    console.log("\nChapters:\n");

    folders.forEach((folder, index) => {
        console.log(
            `${index + 1}. ${folder}`
        );
    });

    const selected =
        parseInt(
            await ask(
                "\nSelect Chapter: "
            )
        );

    const folder =
        folders[selected - 1];

    if (!folder) {
        console.log(
            "\nInvalid selection.\n"
        );
        return;
    }

    const folderPath =
        path.join(
            LESSONS_DIR,
            folder
        );

    const pages =
        fs.readdirSync(folderPath)
            .filter(file =>
                file.endsWith(".html")
            )
            .sort();

    console.log("\nPages:\n");

    if (!pages.length) {
        console.log("(0 pages found)");
    } else {

        pages.forEach((page, index) => {
            console.log(
                `${index + 1}. ${page}`
            );
        });
    }

    const pageName =
        await ask(
            "\nPage Name: "
        );

    const slug =
        slugify(pageName);

    const duplicate =
        pages.find(page =>
            page.endsWith(
                `${slug}.html`
            )
        );

    if (duplicate) {
        console.log(
            "\nPage already exists.\n"
        );
        return;
    }

    const order =
        getNextPageNumber(
            folderPath
        );

    const fileName =
        `${order}-${slug}.html`;

    const filePath =
        path.join(
            folderPath,
            fileName
        );

    const template =
`<h1>Edit Me</h1>

<div class="callout">
    Generated by scaffold.
</div>

<p>
File:
${filePath}
</p>
`;

    fs.writeFileSync(
        filePath,
        template
    );

    console.log(
        `\n✓ Created ${fileName}\n`
    );
}

function rebuildNavigation() {

    try {

        execSync(
            "node build-nav.js",
            {
                stdio: "inherit"
            }
        );

        console.log(
            "\n✓ Navigation rebuilt\n"
        );

    } catch (error) {

        console.log(
            "\nFailed to rebuild navigation.\n"
        );
    }
}

function stats() {

    const folders =
        getFolders();

    let pages = 0;

    folders.forEach(folder => {

        const folderPath =
            path.join(
                LESSONS_DIR,
                folder
            );

        pages +=
            fs.readdirSync(folderPath)
                .filter(file =>
                    file.endsWith(".html")
                )
                .length;
    });

    console.log(`
====================================
Documentation Scaffold Generator
====================================

Total Chapters: ${folders.length}
Total Pages: ${pages}

`);
}

async function main() {

    while (true) {

        stats();

        console.log(`
1. Create Chapter
2. Create Page
3. Rebuild Navigation
4. Exit
`);

        const choice =
            await ask(
                "Select Action: "
            );

        switch (choice) {

            case "1":
                await createChapter();
                break;

            case "2":
                await createPage();
                break;

            case "3":
                rebuildNavigation();
                break;

            case "4":
                rl.close();
                return;

            default:
                console.log(
                    "\nInvalid choice.\n"
                );
        }
    }
}

main();